"""empty message

Revision ID: 2ea59e940cd1
Revises: d46aafacf51b
Create Date: 2019-01-09 22:38:05.084920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea59e940cd1'
down_revision = 'd46aafacf51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('C_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('H_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('U_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'user', ['U_id'], ['Id'])
    op.create_foreign_key(None, 'order', 'configuration', ['C_id'], ['Id'])
    op.create_foreign_key(None, 'order', 'host', ['H_id'], ['Id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'U_id')
    op.drop_column('order', 'H_id')
    op.drop_column('order', 'C_id')
    # ### end Alembic commands ###
