"""empty message

Revision ID: 3ff5227377d4
Revises: a28b9ec0cce7
Create Date: 2019-03-13 23:36:19.053230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff5227377d4'
down_revision = 'a28b9ec0cce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.String(length=64), nullable=True),
    sa.Column('c_address', sa.String(length=256), nullable=True),
    sa.Column('c_phone', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinema')
    # ### end Alembic commands ###
