"""empty message

Revision ID: 525e6d8b5066
Revises: aa94e4498d5a
Create Date: 2019-03-14 22:49:05.311949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525e6d8b5066'
down_revision = 'aa94e4498d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_start_time', sa.DateTime(), nullable=True),
    sa.Column('movie_end_time', sa.DateTime(), nullable=True),
    sa.Column('movie_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
