"""empty message

Revision ID: a28b9ec0cce7
Revises: db1022a9e97c
Create Date: 2019-03-13 22:42:26.553375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28b9ec0cce7'
down_revision = 'db1022a9e97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cu_name', sa.String(length=64), nullable=True),
    sa.Column('_cu_password', sa.String(length=128), nullable=True),
    sa.Column('cu_permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cu_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinema_user')
    # ### end Alembic commands ###
