"""empty message

Revision ID: aa94e4498d5a
Revises: da6096f70e99
Create Date: 2019-03-14 20:30:13.790402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa94e4498d5a'
down_revision = 'da6096f70e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('o_movie', sa.Integer(), nullable=True),
    sa.Column('o_user', sa.Integer(), nullable=True),
    sa.Column('o_create_time', sa.DateTime(), nullable=True),
    sa.Column('o_status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['o_movie'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['o_user'], ['cinema_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_order')
    # ### end Alembic commands ###
