"""empty message

Revision ID: d46aafacf51b
Revises: 
Create Date: 2019-01-09 22:34:28.318423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46aafacf51b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('C_account', sa.String(length=64), nullable=True),
    sa.Column('C_password', sa.String(length=16), nullable=True),
    sa.Column('C_system', sa.String(length=64), nullable=True),
    sa.Column('C_ip', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('C_ip')
    )
    op.create_table('host',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Disk_space', sa.Integer(), nullable=True),
    sa.Column('Monthly_data_transfer', sa.Integer(), nullable=True),
    sa.Column('FTP_accounts', sa.Integer(), nullable=True),
    sa.Column('Email_boxes', sa.Integer(), nullable=True),
    sa.Column('Free_domains', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('order',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('user',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('U_name', sa.String(length=16), nullable=True),
    sa.Column('U_pwd', sa.String(length=128), nullable=True),
    sa.Column('U_email', sa.String(length=64), nullable=True),
    sa.Column('U_phone', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('U_email'),
    sa.UniqueConstraint('U_name'),
    sa.UniqueConstraint('U_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('order')
    op.drop_table('host')
    op.drop_table('configuration')
    # ### end Alembic commands ###
