"""empty message

Revision ID: db1022a9e97c
Revises: 5109257e92ea
Create Date: 2019-03-13 21:42:19.279834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1022a9e97c'
down_revision = '5109257e92ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m_name', sa.String(length=64), nullable=True),
    sa.Column('m_duration', sa.Integer(), nullable=True),
    sa.Column('m_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('m_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
